# Multiple app config
DEVELOPMENT: &dev
    APP_NAME: 'zeus'
    APP_TYPE: 'bottle'
    APP_BASE: 'bottle'
    MODULE: 'zeus:app'
    DEBUG: true

STAGING:
    <<: *dev

PRODUCTION:
    <<: *dev
    DEBUG: false
    MAIL_DEBUG: false
