# Multiple app config
DEVELOPMENT: &dev
    APP_NAME: 'apollo'
    APP_TYPE: 'app'
    APP_BASE: 'bottle'
    MODULE: 'apollo:app'
    DEBUG: true

STAGING:
    <<: *dev

PRODUCTION:
    <<: *dev
    DEBUG: false
    MAIL_DEBUG: false
