# Multiple app config
DEVELOPMENT: &dev
    APP_NAME: 'blog'
    APP_TYPE: 'bottle'
    APP_BASE: 'bottle'
    MODULE: 'blog:app'
    DEBUG: true

    CONTENT_PATH: 'templates/'

STAGING:
    <<: *dev

PRODUCTION:
    <<: *dev
    DEBUG: false
    MAIL_DEBUG: false
